### ISSUE TITLE
[NLU] Testing PiSSA on the GLUE Benchmark with RoBERTa-Base Model?

### ISSUE THREAD

**Issue by SKDDJ** [GraphPKU/PiSSA#8]
Hello, @fxmeng , @MFX12138 

I hope all is well with the PiSSA team. I'm currently using the GLUE benchmark to evaluate the performance of multiple LoRA methods. I was wondering if there have been any benchmarks on the GLUE dataset using the RoBERTa-Base model in conjunction with PiSSA. I've tried PiSSA on GLUE but it seems that training took a long time compared to regular LoRA methods.

So I'm eager to know whether this has been experimented with or if there are results that I could refer to.

Specific Questions:
1. Has the PiSSA integration been tested with the RoBERTa-Base model on any of the GLUE benchmark tasks?
2. If so, are there published results or preprints that detail the performance metrics achieved in this setup?

Looking forward to your response and any insights you may have on this matter.

Best regards

**Comment by fxmeng** [comment]
Hey, thanks for interesting in PiSSA,
We indeed have plans to test PiSSA on the RoBERTa-Base model and the GLUE benchmark, and we will update our paper accordingly. However, due to recent engagements, it may take some time before we can provide results. 
You are also welcome to conduct this experiment yourself. Regarding your observation that PiSSA training took longer compared to regular LoRA, this should not be the case. In principle, the structures of PiSSA and LoRA are identical, and the training time should be the same. 
You may want to carefully check your `perf_config` to ensure it is properly aligned. Additionally, you can share your configuration file, and we will examine it to identify any potential issues.
